# Generated by Django 2.0.1 on 2021-06-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_performer_performer_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer_info',
            name='performer',
        ),
        migrations.DeleteModel(
            name='Performer',
        ),
        migrations.DeleteModel(
            name='Performer_info',
        ),
    ]
