# Generated by Django 2.2.13 on 2021-06-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30, verbose_name='账号')),
                ('operate_type', models.CharField(default='数据填报', max_length=30, verbose_name='操作类型')),
                ('data_model', models.CharField(max_length=30, verbose_name='填报模版')),
                ('file_name', models.TextField(default='-', max_length=200, verbose_name='上传文件名')),
                ('operate_time', models.DateTimeField(verbose_name='操作时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operate_log',
                'ordering': ['-operate_time'],
            },
        ),
    ]
