# Generated by Django 2.2.13 on 2021-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_doubleeleven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleeleven',
            name='sales',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='商品销量'),
        ),
        migrations.AlterField(
            model_name='doubleeleven',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='成交金额'),
        ),
    ]
